### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/BMP180_Breakout_Arduino_Library#3]
In one place in SFE_BMP180.cpp, there is a while-loop after the Wire.requestFrom() call. That while-loop is not needed.

When the Wire.requestFrom() function returns, the I2C transaction has completely finished and the received data is in the receive buffer in the Wire library. The Wire.read() only reads data from that buffer.

When there was a I2C bus error or I2C collision, there would be less bytes received, and that while-loop would halt the sketch.

**Comment by mgrusin** [comment]
Good catch, thank you!

**Comment by Grahldg** [comment]
Thank you for bringing this to our attention.  Unfortunately this product is retired.  The repository will remain available as an archive for reference, but will no longer be maintained.  If you have further questions about this product, please refer to our [forum](https://forum.sparkfun.com).
