### ISSUE TITLE
Include in Arduino IDE library manager?

### ISSUE THREAD

**Issue by awickert** [sparkfun/BMP180_Breakout_Arduino_Library#7]
Could you open an issue to have this library be automatically found by the IDE?
https://github.com/arduino/Arduino/issues
Thanks!

**Comment by Grahldg** [comment]
Thank you for your suggestion.  Unfortunately this product is retired.  The repository will remain available as an archive for reference, but will no longer be maintained.  If you have further questions about this product, please refer to our [forum](https://forum.sparkfun.com).
